### ISSUE TITLE
Error when adding github webhook service

### ISSUE THREAD

**Issue by kfatehi** [matrix-org/go-neb#139]
I'm sure I am doing something wrong here, but I have tried both the YAML way and the HTTP way of configuring a github webhook service and both fail.

The YAML way crashes the program entirely with output like this (of varying lengths each time, so this is just a small slice of the stacktrace):

```
keyvan@lab:~/workspace/matrix-stuff/go-neb$ ./start.sh
INFO[0000] Go-NEB ({BindAddress::4050 DatabaseType:sqlite3 DatabaseURL:go-neb.db?_busy_timeout=5000 BaseURL:http://localhost:4050 LogDir: ConfigFile:config.yaml})
INFO[0000] Inserted 1 clients
INFO[0000] Inserted 1 realms
INFO[0000] Inserted 0 sessions
INFO[0000] Created new client                            auto_join_rooms=true since= sync=true user_id=@bot:synapse.keyvan.pw
PANI[0000] Failed to insert services                     error=config: Service[0] : sql: no rows in result set
panic: (*logrus.Entry) (0xc01780,0xc820190b40)

goroutine 1 [running]:
github.com/Sirupsen/logrus.Entry.log(0xc82001a480, 0xc820235590, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc8201eefe0, ...)
        /home/keyvan/workspace/matrix-stuff/go-neb/vendor/src/github.com/Sirupsen/logrus/entry.go:113 +0x618
github.com/Sirupsen/logrus.(*Entry).Panic(0xc820190b00, 0xc82016faf0, 0x1, 0x1)
        /home/keyvan/workspace/matrix-stuff/go-neb/vendor/src/github.com/Sirupsen/logrus/entry.go:158 +0x99
main.setup(0xc82000e00d, 0x5, 0xc82000e04e, 0x7, 0xc82001000d, 0x1c, 0xc82000e029, 0x15, 0x0, 0x0, ...)
        /home/keyvan/workspace/matrix-stuff/go-neb/src/github.com/matrix-org/go-neb/goneb.go:187 +0x1459
main.main()
        /home/keyvan/workspace/matrix-stuff/go-neb/src/github.com/matrix-org/go-neb/goneb.go:241 +0x6f1
```

My services block looked like this:

```yaml
services:
  - ID: "echo_service"
    Type: "echo"
    UserID: "@bot:synapse.keyvan.pw"
    Config: {}
  - ID: "github_webhook_service"
    Type: "github-webhook"
    UserID: "@bot:synapse.keyvan.pw"
    Config:
      RealmID: "github_realm"
      ClientUserID: "@kfatehi:synapse.keyvan.pw" # needs to be an authenticated user so Go-NEB can create webhooks.
      Rooms:
        "!QfZXlpwcvRDuRfbFSr:synapse.keyvan.pw":
          Repos:
            "kfatehi/matrix-appservice-imessage":
              Events: ["push", "pull_request", "issues"]
```

I eventually gave up doing it with YAML and did it the HTTP way with curl

This time I was successful in actually adding an echo service (I could not even do that with the YAML way, it would die with the same error) and confirmed it to be working. However, when trying to add the github service I'd get a similar error as an HTTP response, and the operation would fail, but at least the program would not crash out.

```
keyvan@lab:~/workspace/matrix-stuff/go-neb$ curl -X POST localhost:4050/admin/configureService --data-binary '{
> "Type": "github-webhook",
> "Id": "github_webhook_service",
> "UserID": "@bot:synapse.keyvan.pw",
> "Config": {
>   "RealmID": "github_realm",
>   "ClientUserID": "@kfatehi:synapse.keyvan.pw",
>   "Rooms": {
>     "!QfZXlpwcvRDuRfbFSr:synapse.keyvan.pw": {
>       "Repos": { "kfatehi/matrix-appservice-imessage": { "Events": [ "push", "pull_request", "issues" ] } }
>       }
>     }
>   }
> }'
{"message":"Failed to register service: sql: no rows in result set"}
keyvan@lab:~/workspace/matrix-stuff/go-neb$
```

The error is really bad. There must be additional context between configuration and why we would care about whether or not some unknown sql query had results.

**Comment by Kegsay** [comment]
Thanks, I'll look into this today.

**Comment by Kegsay** [comment]
So this happens when you try to create a service and give it an unknown `UserID`. Check your `clients` section for a user with that ID.

I can confirm that when there is a client with that user ID in `clients`, it works correctly.

**Comment by Kegsay** [comment]
Keeping this open until there's a better error message.

**Comment by Kegsay** [comment]
https://github.com/matrix-org/go-neb/commit/34ea2d06ce61e5af5652a75f3e2a7bb3f64e37c9#diff-250f1350b07f5e2389b35e86c79cd9f3R100

**Comment by kfatehi** [comment]
Thanks @Kegsay 

I can report that go-neb is now working well for me now for webhooks!
